services:
  db:
    image: mariadb:11
    container_name: mysql_db

    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: sust_cafeteria
      MARIADB_USER: user
      MARIADB_PASSWORD: pass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend1:
    image: voideye/sustcafe-backend

    container_name: backend1

    restart: unless-stopped

    environment:
      PORT: 8000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: sust_cafeteria
      JWT_SECRET: secret_key
      HOST_URL: http://localhost
      CLIENT_URL: http://localhost

    depends_on:
      db:
        condition: service_healthy

  backend2:
    image: voideye/sustcafe-backend

    container_name: backend2

    restart: unless-stopped

    environment:
      PORT: 8000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: sust_cafeteria
      JWT_SECRET: secret_key
      HOST_URL: http://localhost
      CLIENT_URL: http://localhost

    depends_on:
      db:
        condition: service_healthy

  backend3:
    image: voideye/sustcafe-backend

    container_name: backend3

    restart: unless-stopped

    environment:
      PORT: 8000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: sust_cafeteria
      JWT_SECRET: secret_key
      HOST_URL: http://localhost
      CLIENT_URL: http://localhost

    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: voideye/sustcafe-frontend

    container_name: frontend

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend1
      - backend2
      - backend3

  adminer:
    image: adminer

    container_name: adminer

    restart: unless-stopped

    ports:
      - "8080:8080"

volumes:
  mysql_data:
