openapi: 3.0.0
info:
  title: SustCafeteria API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /user:
    post:
      $ref: "./schemas/user/post.yaml"
    get:
      $ref: "./schemas/user/get.yaml"
  /user/{id}:
    get:
      $ref: "./schemas/userId/get.yaml"
  /user/login:
    post:
      $ref: "./schemas/userLogin/post.yaml"
    get:
      $ref: "./schemas/userLogin/get.yaml"

      # ------------Inventory----------------
  /inventory:
    post:
      $ref: "./schemas/inventoryAdmin/post.yaml"
    get:
      $ref: "./schemas/inventory/get.yaml"
  /inventory/low-stock:
    get:
      $ref: "./schemas/inventory/low-stock.yaml"
  /inventory/available:
    get:
      $ref: "./schemas/inventory/available.yaml"
  /inventory/{id}:
    get:
      $ref: "./schemas/inventory/get-id.yaml"
    delete:
      $ref: "./schemas/inventoryAdmin/delete.yaml"
  /inventory/{id}/quantity:
    put:
      $ref: "./schemas/inventoryAdmin/quantity.yaml"
  /inventory/{id}/info:
    put:
      $ref: "./schemas/inventoryAdmin/info.yaml"

      # ------------Supplier----------------
  /supplier:
    post:
      $ref: "./schemas/supplier/post.yaml"
    get:
      $ref: "./schemas/supplier/get.yaml"
    delete:
      $ref: "./schemas/supplier/delete-all.yaml"
  /supplier/{id}:
    get:
      $ref: "./schemas/supplier/get-id.yaml"
    delete:
      $ref: "./schemas/supplier/delete.yaml"
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
